### ISSUE TITLE
Need a place to host static files.

### ISSUE THREAD

**Issue by Vishnum98** [macports/macports-gsoc2018-webapp#4]
It is extremely difficlut to sort out the Static file stuff in heroku . 

Static files like : css , js , images .. all such files.

That's why it's currently present in the html file itself.

But at the end i prefer macports domain.

**Comment by l2dy** [comment]
You can use these for free:
* GitHub Pages
GitHub Pages sites are subject to the following usage limits:
  * GitHub Pages source repositories have a recommended limit of 1GB.
  * Published GitHub Pages sites may be no larger than 1 GB.
  * GitHub Pages sites have a soft bandwidth limit of 100GB per month.
  * GitHub Pages sites have a soft limit of 10 builds per hour.
* [Netlify](https://www.netlify.com/docs/)
Network Bandwidth: 100GB/month - Soft
Storage: 100GB - Soft
* [Now](https://zeit.co/pricing)
* [Surge](https://surge.sh/help/getting-started-with-surge)

But Heroku should support static file hosting.

**Comment by mojca** [comment]
I didn't try it myself, but I'm almost sure that this is not something specific to Heroku and I'm almost sure that this should work out of the box when configured properly.

See https://docs.djangoproject.com/en/2.0/howto/static-files/ and let us know if there's something you don't understand. If you really cannot make it work on Heroku, create a new branch and set it up in a way that will work on your computer with instructions above and then we can check what goes wrong with Heroku, but I'm almost sure that this is just a simple configuration issue.

Minor nitpicking: try to stick to grammar rules when writing. The word "I" is written with capital letter, there should be no space before commas, dots, colons, there is no such puncuation mark as two dots. Use three dots instead.

**Comment by Vishnum98** [comment]
Implemented static files on django and heroku successfully.

**Comment by JacksonIsaac** [comment]
Good progress. Keep it up!
